name: Update sbo-maintainer-tools
on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Update the version of sbo-maintainer-tools packaged.
        run: |
          CWD="$(pwd)"
          wget -O - https://github.com/SlackBuildsOrg/slackbuilds/tarball/master | tar xz
          (
            cd SlackBuildsOrg-slackbuilds-*
            cd system/sbo-maintainer-tools
            . sbo-maintainer-tools.info

            sed -i "s/VERSION=.*$/VERSION=$VERSION/" $CWD/build_sbo-maintainer-tools.sh
            sed -i "s/MD5SUM=.*$/MD5SUM=$MD5SUM/" $CWD/build_sbo-maintainer-tools.sh
            sed -i "s,DOWNLOAD=.*$,DOWNLOAD=$DOWNLOAD," $CWD/build_sbo-maintainer-tools.sh

            printf 'NEXT_VERSION=%s\n' "$VERSION" >> $GITHUB_ENV
          )
          rm -rf SlackBuildsOrg-slackbuilds-*

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: "Update sbo-maintainer-tools to ${{ env.NEXT_VERSION }}"
            title: "Update sbo-maintainer-tools to ${{ env.NEXT_VERSION }}"
            body: |
              - sbo-maintainer-tools - ${{ env.NEXT_VERSION }}

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-sbo-maintainer-tools-${{ env.NEXT_VERSION }}
